version: "3.7"
services:
  api:
    container_name: api
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - "8080:3000"
    networks:
      - net
networks:
  net:
